# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'league.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import mysql.connector as mc

from dbconnection import cursor, connection


class Ui_League(object):
    def add(self):
        try:

            league_id = self.le_league_id.text()
            league_name = self.le_league_name.text()
            reward = self.le_reward.text()

            sql = "INSERT INTO league VALUES (%s, %s, %s)"
            value = (league_id, league_name, reward)

            cursor.execute(sql, value)

            connection.commit()
            print("başarıyla eklendi")
            self.display()

        except mc.Error as e:
            print("Bilgi eklenemedi")

    def display(self):
        try:
            
            sql = "SELECT * FROM league"
            cursor.execute(sql)

            result = cursor.fetchall()

            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,
                                             column_number, QTableWidgetItem(str(data)))

            print("başarıyla gösterildi")



        except mc.Error as e:
            print("Tablo gösterilemedi")

    def update(self):
        try:

            sql = """SELECT * FROM league"""
            cursor.execute(sql)
            result = cursor.fetchall()

            league_id = self.le_league_id.text()
            league_name = self.le_league_name.text()
            reward = self.le_reward.text()

            for row in enumerate(result):
                if row[0] == self.tableWidget.currentRow():
                    data = row[1]
                    LeagueId = data[0]
                    LeagueName = data[1]
                    Reward = data[2]

                    cursor.execute('''UPDATE league SET league_id = %s, league_name = %s, reward = %s WHERE league_id = %s AND league_name = %s AND reward = %s''',
                                   (league_id, league_name, reward, LeagueId, LeagueName, Reward))

                    connection.commit()
                    self.display()

        except mc.Error as e:
            print("Bilgi Güncellenemedi")

    def delete(self):
        try:
            sql = "SELECT * FROM league"

            cursor.execute(sql)
            result = cursor.fetchall()

            for row in enumerate(result):
                if row[0] == self.tableWidget.currentRow():
                    data = row[1]
                    LeagueId = data[0]
                    LeagueName = data[1]
                    Reward = data[2]

                    cursor.execute(
                        """ DELETE FROM league WHERE league_id = %s AND league_name = %s AND reward = %s""", (LeagueId, LeagueName, Reward))
                    connection.commit()
                    self.display()
        except mc.Error as e:
            print("Bilgi Silinemedi")

    def search(self):
        try:

            league_id_text = self.le_league_id.text() 
            league_name_text = self.le_league_name.text() 
            reward_text = self.le_reward.text() 

            sql = "SELECT * FROM league WHERE league_id LIKE %s or league_name LIKE %s or reward LIKE %s"
            cursor.execute(sql, (league_id_text + '%', league_name_text + '%', reward_text + '%'))

            result = cursor.fetchall()

            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,
                                             column_number, QTableWidgetItem(str(data)))
            
            print("aranan kısımlar başarıyla gösterildi")

        except mc.Error as e:
            print("Aranan Bilgi Bulunamadı")
            print(e)

    def reset(self):
        self.le_league_id.setText("")
        self.le_league_name.setText("")
        self.le_reward.setText("")

    def clicked(self):
        sql = "SELECT * FROM league"

        cursor.execute(sql)
        result = cursor.fetchall()

        for row in enumerate(result):
            if row[0] == self.tableWidget.currentRow():
                data = row[1]
                LeagueId = data[0]
                LeagueName = data[1]
                Reward = data[2]

                self.le_league_id.setText(str(LeagueId))
                self.le_league_name.setText(str(LeagueName))
                self.le_reward.setText(str(Reward))



    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(945, 694)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(720, 110, 231, 601))
        self.frame.setStyleSheet("\n"
                                 "background-color: rgb(106, 106, 106);\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnAdd = QtWidgets.QPushButton(self.frame)
        self.btnAdd.setGeometry(QtCore.QRect(40, 10, 131, 71))
        self.btnAdd.setStyleSheet("\n"
                                  "QPushButton::hover\n"
                                  "{\n"
                                  "background-color: rgb(0, 0, 139);\n"
                                  "color: rgb(255, 255, 255);\n"
                                  "}\n"
                                  "QPushButton{\n"
                                  "\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "font: 81 14pt \"Roboto Slab ExtraBold\";\n"
                                  "border-radius:20px;\n"
                                  "}\n"
                                  "")
        self.btnAdd.setObjectName("btnAdd")
        self.btnAdd.clicked.connect(self.add)


        self.btnDisplay = QtWidgets.QPushButton(self.frame)
        self.btnDisplay.setGeometry(QtCore.QRect(40, 110, 131, 71))
        self.btnDisplay.setStyleSheet("\n"
                                      "QPushButton::hover\n"
                                      "{\n"
                                      "background-color: rgb(0, 0, 139);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "QPushButton{\n"
                                      "\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "font: 81 14pt \"Roboto Slab ExtraBold\";\n"
                                      "border-radius:20px;\n"
                                      "}\n"
                                      "")
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnDisplay.clicked.connect(self.display)


        self.btnUpdate = QtWidgets.QPushButton(self.frame)
        self.btnUpdate.setGeometry(QtCore.QRect(40, 210, 131, 71))
        self.btnUpdate.setStyleSheet("\n"
                                     "QPushButton::hover\n"
                                     "{\n"
                                     "background-color: rgb(0, 0, 139);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "}\n"
                                     "QPushButton{\n"
                                     "\n"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "font: 81 14pt \"Roboto Slab ExtraBold\";\n"
                                     "border-radius:20px;\n"
                                     "}\n"
                                     "")
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnUpdate.clicked.connect(self.update)


        self.btnDelete = QtWidgets.QPushButton(self.frame)
        self.btnDelete.setGeometry(QtCore.QRect(40, 310, 131, 71))
        self.btnDelete.setStyleSheet("\n"
                                     "QPushButton::hover\n"
                                     "{\n"
                                     "background-color: rgb(0, 0, 139);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "}\n"
                                     "QPushButton{\n"
                                     "\n"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "font: 81 14pt \"Roboto Slab ExtraBold\";\n"
                                     "border-radius:20px;\n"
                                     "}\n"
                                     "")
        self.btnDelete.setObjectName("btnDelete")
        self.btnDelete.clicked.connect(self.delete)


        self.btnSearch = QtWidgets.QPushButton(self.frame)
        self.btnSearch.setGeometry(QtCore.QRect(40, 410, 131, 71))
        self.btnSearch.setStyleSheet("\n"
                                     "QPushButton::hover\n"
                                     "{\n"
                                     "background-color: rgb(0, 0, 139);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "}\n"
                                     "QPushButton{\n"
                                     "\n"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "font: 81 14pt \"Roboto Slab ExtraBold\";\n"
                                     "border-radius:20px;\n"
                                     "}\n"
                                     "")
        self.btnSearch.setObjectName("btnSearch")
        self.btnSearch.clicked.connect(self.search)


        self.btnReset = QtWidgets.QPushButton(self.frame)
        self.btnReset.setGeometry(QtCore.QRect(40, 500, 131, 71))
        self.btnReset.setStyleSheet("\n"
                                    "QPushButton::hover\n"
                                    "{\n"
                                    "background-color: rgb(0, 0, 139);\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    "QPushButton{\n"
                                    "\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "font: 81 14pt \"Roboto Slab ExtraBold\";\n"
                                    "border-radius:20px;\n"
                                    "}\n"
                                    "")
        self.btnReset.setObjectName("btnReset")
        self.btnReset.clicked.connect(self.reset)


        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 951, 111))
        self.frame_2.setStyleSheet("background-color:rgb(40, 40, 40);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_main = QtWidgets.QLabel(self.frame_2)
        self.lbl_main.setGeometry(QtCore.QRect(280, 30, 321, 51))
        self.lbl_main.setStyleSheet("color: white;")
        self.lbl_main.setObjectName("lbl_main")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 110, 721, 211))
        self.frame_3.setStyleSheet("background-color: rgb(197, 197, 197);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.le_league_id = QtWidgets.QLineEdit(self.frame_3)
        self.le_league_id.setGeometry(QtCore.QRect(260, 40, 301, 31))
        self.le_league_id.setStyleSheet("\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "")
        self.le_league_id.setObjectName("le_league_id")
        self.le_league_name = QtWidgets.QLineEdit(self.frame_3)
        self.le_league_name.setGeometry(QtCore.QRect(260, 100, 301, 31))
        self.le_league_name.setStyleSheet("\n"
                                          "background-color: rgb(255, 255, 255);\n"
                                          "")
        self.le_league_name.setObjectName("le_league_name")
        self.le_reward = QtWidgets.QLineEdit(self.frame_3)
        self.le_reward.setGeometry(QtCore.QRect(260, 160, 301, 31))
        self.le_reward.setStyleSheet("\n"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "")
        self.le_reward.setObjectName("le_reward")
        self.lbl_id = QtWidgets.QLabel(self.frame_3)
        self.lbl_id.setGeometry(QtCore.QRect(90, 40, 141, 31))
        self.lbl_id.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_id.setObjectName("lbl_id")
        self.lbl_name = QtWidgets.QLabel(self.frame_3)
        self.lbl_name.setGeometry(QtCore.QRect(90, 100, 141, 31))
        self.lbl_name.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_rwrd = QtWidgets.QLabel(self.frame_3)
        self.lbl_rwrd.setGeometry(QtCore.QRect(90, 160, 141, 31))
        self.lbl_rwrd.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_rwrd.setObjectName("lbl_rwrd")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 320, 721, 381))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setVerticalScrollMode(
            QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.clicked.connect(self.clicked)

        header = self.tableWidget.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnAdd.setText(_translate("Form", "ADD"))
        self.btnDisplay.setText(_translate("Form", "DISPLAY"))
        self.btnUpdate.setText(_translate("Form", "UPDATE"))
        self.btnDelete.setText(_translate("Form", "DELETE"))
        self.btnSearch.setText(_translate("Form", "SEARCH"))
        self.btnReset.setText(_translate("Form", "RESET"))
        self.lbl_main.setText(_translate(
            "Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">LEAGUE MANAGEMENT</span></p></body></html>"))
        self.lbl_id.setText(_translate("Form", "League Id"))
        self.lbl_name.setText(_translate("Form", "League Name"))
        self.lbl_rwrd.setText(_translate("Form", "Reward"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "League Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "League Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Reward"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_League()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
