# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from players import Ui_Players
from league import Ui_League
from matches import Ui_Matches
from teams import Ui_Teams
from score_set import Ui_Scores


class Ui_Form(object):

    def open_players_Window(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Players()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_league_Window(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_League()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_matches_Window(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Matches()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_teams_Window(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Teams()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_scores_Window(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Scores()
        self.ui.setupUi(self.window)
        self.window.show()

    

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1031, 708)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("font-size: 30px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3, clicked = lambda: self.open_teams_Window())
        self.pushButton.setGeometry(QtCore.QRect(250, 160, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3, clicked = lambda: self.open_league_Window())
        self.pushButton_2.setGeometry(QtCore.QRect(410, 160, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(820, 160, 121, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3, clicked = lambda: self.open_players_Window())
        self.pushButton_4.setGeometry(QtCore.QRect(60, 160, 151, 51))
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3, clicked = lambda: self.open_scores_Window())
        self.pushButton_6.setGeometry(QtCore.QRect(620, 160, 121, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "FOOTBALL LEAGUE MANAGEMENT SYSTEM"))
        self.pushButton.setText(_translate("Form", "TEAM MANAGEMENT"))
        self.pushButton_2.setText(_translate("Form", "LEAGUE MANAGAMENT"))
        self.pushButton_3.setText(_translate("Form", "FIXTURE"))
        self.pushButton_4.setText(_translate("Form", "PLAYER MANAGEMENT"))
        self.pushButton_6.setText(_translate("Form", "MATCH SCORE SET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
