# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'league.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from PyQt5.QtWidgets import QTableWidgetItem
import mysql.connector as mc

from dbconnection import cursor, connection

class Ui_Players(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1222, 869)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1221, 871))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 110, 991, 291))
        self.frame_3.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pl_first_name = QtWidgets.QLineEdit(self.frame_3)
        self.pl_first_name.setGeometry(QtCore.QRect(260, 70, 301, 31))
        self.pl_first_name.setStyleSheet("    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.pl_first_name.setObjectName("pl_first_name")
        self.pl_last_name = QtWidgets.QLineEdit(self.frame_3)
        self.pl_last_name.setGeometry(QtCore.QRect(260, 110, 301, 31))
        self.pl_last_name.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pl_last_name.setObjectName("pl_last_name")
        self.lbl_id = QtWidgets.QLabel(self.frame_3)
        self.lbl_id.setGeometry(QtCore.QRect(90, 30, 141, 31))
        self.lbl_id.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_id.setObjectName("lbl_id")
        self.lbl_first_name = QtWidgets.QLabel(self.frame_3)
        self.lbl_first_name.setGeometry(QtCore.QRect(90, 70, 141, 31))
        self.lbl_first_name.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_first_name.setObjectName("lbl_first_name")
        self.lbl_last_name = QtWidgets.QLabel(self.frame_3)
        self.lbl_last_name.setGeometry(QtCore.QRect(90, 110, 141, 31))
        self.lbl_last_name.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_last_name.setObjectName("lbl_last_name")
        self.lbl_position = QtWidgets.QLabel(self.frame_3)
        self.lbl_position.setGeometry(QtCore.QRect(90, 190, 141, 31))
        self.lbl_position.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_position.setObjectName("lbl_position")
        self.pl_country = QtWidgets.QLineEdit(self.frame_3)
        self.pl_country.setGeometry(QtCore.QRect(260, 230, 301, 31))
        self.pl_country.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.pl_country.setText("")
        self.pl_country.setObjectName("pl_country")
        self.lbl_country = QtWidgets.QLabel(self.frame_3)
        self.lbl_country.setGeometry(QtCore.QRect(90, 230, 141, 31))
        self.lbl_country.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_country.setObjectName("lbl_country")
        self.lbl_age = QtWidgets.QLabel(self.frame_3)
        self.lbl_age.setGeometry(QtCore.QRect(90, 150, 141, 31))
        self.lbl_age.setStyleSheet("font: 87 12pt \"Roboto Slab Black\";")
        self.lbl_age.setObjectName("lbl_age")
        self.pl_age = QtWidgets.QLineEdit(self.frame_3)
        self.pl_age.setGeometry(QtCore.QRect(260, 150, 301, 31))
        self.pl_age.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pl_age.setText("")
        self.pl_age.setObjectName("pl_age")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(260, 30, 301, 31))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color: #fff;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.pl_position = QtWidgets.QComboBox(self.frame_3)
        self.pl_position.setGeometry(QtCore.QRect(260, 190, 301, 31))
        self.pl_position.setStyleSheet("QComboBox{\n"
"    background-color: #fff;\n"
"}\n"
"")
        self.pl_position.setObjectName("pl_position")
        self.pl_position.addItem("")
        self.pl_position.addItem("")
        self.pl_position.addItem("")
        self.pl_position.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(990, 0, 231, 871))
        self.frame_2.setStyleSheet("\n"
"background-color: rgb(106, 106, 106);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnAdd = QtWidgets.QPushButton(self.frame_2)
        self.btnAdd.clicked.connect(self.add_data)
        self.btnAdd.setGeometry(QtCore.QRect(40, 10, 131, 71))
        self.btnAdd.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(0, 0, 139);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"font: 81 14pt \"Roboto Slab ExtraBold\";\n"
"border-radius:20px;\n"
"}\n"
"")
        self.btnAdd.setObjectName("btnAdd")
        self.btnDisplay = QtWidgets.QPushButton(self.frame_2)
        self.btnDisplay.clicked.connect(self.display_data)
        self.btnDisplay.setGeometry(QtCore.QRect(40, 110, 131, 71))
        self.btnDisplay.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(0, 0, 139);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"font: 81 14pt \"Roboto Slab ExtraBold\";\n"
"border-radius:20px;\n"
"}\n"
"")
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnUpdate = QtWidgets.QPushButton(self.frame_2)
        self.btnUpdate.clicked.connect(self.update_data)
        self.btnUpdate.setGeometry(QtCore.QRect(40, 210, 131, 71))
        self.btnUpdate.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(0, 0, 139);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"font: 81 14pt \"Roboto Slab ExtraBold\";\n"
"border-radius:20px;\n"
"}\n"
"")
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnDelete = QtWidgets.QPushButton(self.frame_2)
        self.btnDelete.clicked.connect(self.delete_data)
        self.btnDelete.setGeometry(QtCore.QRect(40, 310, 131, 71))
        self.btnDelete.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(0, 0, 139);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"font: 81 14pt \"Roboto Slab ExtraBold\";\n"
"border-radius:20px;\n"
"}\n"
"")
        self.btnDelete.setObjectName("btnDelete")
        self.btnSearch = QtWidgets.QPushButton(self.frame_2)
        self.btnSearch.setGeometry(QtCore.QRect(40, 410, 131, 71))
        self.btnSearch.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(0, 0, 139);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"font: 81 14pt \"Roboto Slab ExtraBold\";\n"
"border-radius:20px;\n"
"}\n"
"")
        self.btnSearch.setObjectName("btnSearch")
        self.btnReset = QtWidgets.QPushButton(self.frame_2)
        self.btnReset.setGeometry(QtCore.QRect(40, 500, 131, 71))
        self.btnReset.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(0, 0, 139);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"font: 81 14pt \"Roboto Slab ExtraBold\";\n"
"border-radius:20px;\n"
"}\n"
"")
        self.btnReset.setObjectName("btnReset")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 991, 111))
        self.frame_5.setStyleSheet("background-color:rgb(40, 40, 40);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lbl_main = QtWidgets.QLabel(self.frame_5)
        self.lbl_main.setGeometry(QtCore.QRect(280, 30, 321, 51))
        self.lbl_main.setStyleSheet("color: white;")
        self.lbl_main.setObjectName("lbl_main")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.clicked.connect(self.table_clicked)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setGeometry(QtCore.QRect(0, 400, 991, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


        self.comboBox.currentIndexChanged[int].connect(self.retrieveText)
        self.fillComboBox()

    def fillComboBox(self):
        teams = self.combobox_teams()
        for key, value in teams.items():
                self.comboBox.addItem(key, value)

    def retrieveText(self, index):
            x = self.comboBox.itemData(index)
            if x is not None:
                global combobox_team_id
                combobox_team_id = (str(x))

    def combobox_teams(self):
        try:
            content = "SELECT team_id, team_name FROM teams"
            cursor.execute(content)
            result = cursor.fetchall()

            dct = dict(map(reversed, result))
            return dct
        except mc.Error as e:
            print("Error occured")
    ###########################################################

    def display_data(self):
        try:
        # CREATE VIEW player_informations AS
        # SELECT teams.team_name, first_name, last_name, age, position, country,COALESCE(SUM(scores.goals),0) as goal ,COALESCE(SUM(scores.assists),0) as asist
        # FROM players
        # LEFT JOIN teams ON players.team_id = teams.team_id
        # LEFT JOIN scores on players.player_id = scores.player_id
        # GROUP BY (players.player_id)
            cursor.execute("""SELECT * FROM `player_informations`""")

            result = cursor.fetchall()

            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(
                        row_number, column_number, QTableWidgetItem(str(data)))
        except mc.Error as e:
            print("Error occured")

    def add_data(self):
        try:
            firstName = self.pl_first_name.text()
            lastName = self.pl_last_name.text()
            age = self.pl_age.text()
            position = self.pl_position.text()
            country = self.pl_country.text()

            query = " INSERT INTO players(team_id,first_name,last_name,age,position,country) VALUES (%s,%s,%s,%s,%s,%s)"
            cursor.execute(query,(combobox_team_id,firstName,lastName,age,position,country))

            connection.commit()
            self.display_data()
        except mc.Error as e:
            print("Error occured",e)

    def delete_data(self):
        try:
            cursor.execute("""SELECT * FROM players""")
            result = cursor.fetchall()
        
            for row in enumerate(result):
                if row[0] == self.tableWidget.currentRow():
                    data = row[1]
                    player_id = data[0]
                    query = "DELETE FROM players WHERE player_id = (%s)"
                    cursor.execute(query,(player_id,))
                    connection.commit()
                    self.display_data()
        except mc.Error as e:
            print("Error occured")

    def update_data(self):
        try:
            teamId = combobox_team_id
            firstName = self.pl_first_name.text()
            lastName = self.pl_last_name.text()
            age = self.pl_age.text()
            position = self.pl_position.currentText()
            country = self.pl_country.text()

            query = "UPDATE players SET team_id=%s,first_name = %s, last_name = %s, age = %s, position = %s, country = %s WHERE player_id = %s"
            value = (teamId,firstName,lastName,age,position,country,playerId)
            cursor.execute(query,value)
            connection.commit()
            self.display_data()
        except mc.Error as e:
            print("Error occured")

    def table_clicked(self):
        try:
            cursor.execute("""SELECT team_id, first_name, last_name, age, position, country, player_id FROM players""")
            result = cursor.fetchall()
            global playerId
            for row in enumerate(result):
                if row[0] == self.tableWidget.currentRow():
                    data = row[1]
                    teamId = data[0]
                    firstName = data[1]
                    lastName = data[2]
                    age = data[3]
                    position = data[4]
                    country = data[5]
                    playerId = data[6]

                    self.comboBox.setCurrentIndex(teamId-1)
                    self.pl_first_name.setText(str(firstName))
                    self.pl_last_name.setText(str(lastName))
                    self.pl_age.setText(str(age))
                    self.pl_position.setCurrentText(position)
                    self.pl_country.setText(str(country))
        except mc.Error as e:
            print("Error occured")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_id.setText(_translate("Form", "Team"))
        self.lbl_first_name.setText(_translate("Form", "First Name"))
        self.lbl_last_name.setText(_translate("Form", "Last Name"))
        self.lbl_position.setText(_translate("Form", "Position"))
        self.lbl_country.setText(_translate("Form", "Country"))
        self.lbl_age.setText(_translate("Form", "Age"))
        self.pl_position.setItemText(0, _translate("Form", "Goalkeeper"))
        self.pl_position.setItemText(1, _translate("Form", "Defender"))
        self.pl_position.setItemText(2, _translate("Form", "Midfielder"))
        self.pl_position.setItemText(3, _translate("Form", "Forward"))
        self.btnAdd.setText(_translate("Form", "ADD"))
        self.btnDisplay.setText(_translate("Form", "DISPLAY"))
        self.btnUpdate.setText(_translate("Form", "UPDATE"))
        self.btnDelete.setText(_translate("Form", "DELETE"))
        self.btnSearch.setText(_translate("Form", "SEARCH"))
        self.btnReset.setText(_translate("Form", "RESET"))
        self.lbl_main.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">PLAYERS</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Team Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Age"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Country"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Goal"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Assist"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Players()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
