# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_score.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox

from dbconnection import cursor, connection


class Ui_Scores(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1188, 302)
        Form.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #fff;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"padding: 5px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"QLabel  {\n"
"    font-size: 20px;\n"
"    color: #FFB000;\n"
"}\n"
"QLineEdit {\n"
"    font-size: 20px;\n"
"    background-color: #fff;\n"
"color: #fff;\n"
"}\n"
"QComboBox {\n"
"    font-size: 20px;\n"
"    background-color: #fff;\n"
"    color: #fff;\n"
"    border: 2px white;\n"
"    border-style: solid;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_3.setStyleSheet("background-color: #17456B;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("background-color: #0F1D2B;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(80, 80, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 111, 21))
        self.label_3.setObjectName("label_3")
        self.ln_player_id = QtWidgets.QLineEdit(self.frame_5)
        self.ln_player_id.setGeometry(QtCore.QRect(240, 180, 221, 31))
        self.ln_player_id.setObjectName("ln_player_id")
        self.cmb_match = QtWidgets.QComboBox(self.frame_5)
        self.cmb_match.setGeometry(QtCore.QRect(240, 70, 371, 31))
        self.cmb_match.setObjectName("cmb_match")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 1041, 51))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(400, 0, 301, 41))
        self.label_4.setStyleSheet("color: #fff;\n"
"font: bold 20px;\n"
"font-size: 30px;")
        self.label_4.setObjectName("label_4")
        self.cmb_team_name = QtWidgets.QComboBox(self.frame_5)
        self.cmb_team_name.setGeometry(QtCore.QRect(240, 120, 221, 31))
        self.cmb_team_name.setObjectName("cmb_team_name")
        self.cmb_goal = QtWidgets.QComboBox(self.frame_5)
        self.cmb_goal.setGeometry(QtCore.QRect(780, 60, 61, 31))
        self.cmb_goal.setObjectName("cmb_goal")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.cmb_goal.addItem("")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(710, 70, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(900, 70, 61, 21))
        self.label_6.setObjectName("label_6")
        self.btnInsert = QtWidgets.QPushButton(self.frame_5)
        self.btnInsert.setGeometry(QtCore.QRect(890, 220, 180, 40))
        self.btnInsert.setObjectName("btnInsert")
        self.cmb_goal_2 = QtWidgets.QComboBox(self.frame_5)
        self.cmb_goal_2.setGeometry(QtCore.QRect(990, 60, 61, 31))
        self.cmb_goal_2.setObjectName("cmb_goal_2")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.cmb_goal_2.addItem("")
        self.verticalLayout_4.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.cmb_match.currentIndexChanged[int].connect(self.retrieveText_matches)
        self.fillComboBox_matches()

        self.cmb_team_name.currentIndexChanged[int].connect(self.retrieveText)
        self.fillComboBox()

    def fillComboBox(self):
        teams = self.combobox_teams()
        for key, value in teams.items():
                self.cmb_team_name.addItem(key, value)

    def retrieveTex_numbers(self, index):
            x = self.cmb_goal.itemData(index)
            if x is not None:
                global combobox_team_id
                combobox_team_id = (str(x))

    def fillComboBox_matches(self):
        matches = self.combobox_matches()
        for key, value in matches.items():
                self.cmb_match.addItem(key, value)

    def retrieveText(self, index):
            x = self.cmb_team_name.itemData(index)
            if x is not None:
                global combobox_team_id
                combobox_team_id = (str(x))

    def retrieveText_matches(self, index):
            x = self.cmb_team_name.itemData(index)
            if x is not None:
                global combobox_match_id
                combobox_match_id = (str(x))
                print(combobox_match_id)

    def combobox_teams(self):
        try:
            content = "SELECT team_id, team_name FROM teams"
            cursor.execute(content)
            result = cursor.fetchall()

            dct = dict(map(reversed, result))
            return dct
        except mc.Error as e:
            print("Error occured")

    def combobox_matches(self):
        try:
            content = """ SELECT matches.match_id, CONCAT(t1.team_name," vs ", t2.team_name) AS `matches` FROM matches JOIN teams as t1 on t1.team_id=matches.home_id JOIN teams as t2 on t2.team_id=matches.away_id """
            cursor.execute(content)
            result = cursor.fetchall()

            dct = dict(map(reversed, result))
            return dct
        except mc.Error as e:
            print("Error occured")

    def set_score(self):
        try:
            matchId = combobox_match_id
            teamId = combobox_team_id
            playerId = self.ln_player_id.text()
            goal = self.cmb_goal.currentText()
            asist = self.cmb_goal_2.currentText()

            query = "INSERT INTO scores (match_id,team_id,player_id,goals,assists) VALUES(%s,%s,%s,%s,%s)"
            values = (matchId,teamId,playerId,goal,asist)
            cursor.execute(query,values)

            connection.commit()
            print("Başarılı")
        except mc.Error as e:
            print("Error occured: ",e)
        

        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Match"))
        self.label_2.setText(_translate("Form", "Team"))
        self.label_3.setText(_translate("Form", "Player Id"))
        self.label_4.setText(_translate("Form", "MATCH SET SCORE"))
        self.cmb_goal.setItemText(0, _translate("Form", "0"))
        self.cmb_goal.setItemText(1, _translate("Form", "1"))
        self.cmb_goal.setItemText(2, _translate("Form", "2"))
        self.cmb_goal.setItemText(3, _translate("Form", "3"))
        self.cmb_goal.setItemText(4, _translate("Form", "4"))
        self.cmb_goal.setItemText(5, _translate("Form", "5"))
        self.cmb_goal.setItemText(6, _translate("Form", "7"))
        self.cmb_goal.setItemText(7, _translate("Form", "8"))
        self.cmb_goal.setItemText(8, _translate("Form", "9"))
        self.cmb_goal.setItemText(9, _translate("Form", "10"))
        self.cmb_goal.setItemText(10, _translate("Form", "11"))
        self.cmb_goal.setItemText(11, _translate("Form", "12"))
        self.cmb_goal.setItemText(12, _translate("Form", "13"))
        self.cmb_goal.setItemText(13, _translate("Form", "14"))
        self.cmb_goal.setItemText(14, _translate("Form", "15"))
        self.cmb_goal.setItemText(15, _translate("Form", "16"))
        self.cmb_goal.setItemText(16, _translate("Form", "17"))
        self.cmb_goal.setItemText(17, _translate("Form", "18"))
        self.cmb_goal.setItemText(18, _translate("Form", "19"))
        self.cmb_goal.setItemText(19, _translate("Form", "20"))
        self.label_5.setText(_translate("Form", "Goal"))
        self.label_6.setText(_translate("Form", "Asist"))
        self.btnInsert.setText(_translate("Form", "SET SCORE"))
        self.btnInsert.clicked.connect(self.set_score)
        self.cmb_goal_2.setItemText(0, _translate("Form", "0"))
        self.cmb_goal_2.setItemText(1, _translate("Form", "1"))
        self.cmb_goal_2.setItemText(2, _translate("Form", "2"))
        self.cmb_goal_2.setItemText(3, _translate("Form", "3"))
        self.cmb_goal_2.setItemText(4, _translate("Form", "4"))
        self.cmb_goal_2.setItemText(5, _translate("Form", "5"))
        self.cmb_goal_2.setItemText(6, _translate("Form", "7"))
        self.cmb_goal_2.setItemText(7, _translate("Form", "8"))
        self.cmb_goal_2.setItemText(8, _translate("Form", "9"))
        self.cmb_goal_2.setItemText(9, _translate("Form", "10"))
        self.cmb_goal_2.setItemText(10, _translate("Form", "11"))
        self.cmb_goal_2.setItemText(11, _translate("Form", "12"))
        self.cmb_goal_2.setItemText(12, _translate("Form", "13"))
        self.cmb_goal_2.setItemText(13, _translate("Form", "14"))
        self.cmb_goal_2.setItemText(14, _translate("Form", "15"))
        self.cmb_goal_2.setItemText(15, _translate("Form", "16"))
        self.cmb_goal_2.setItemText(16, _translate("Form", "17"))
        self.cmb_goal_2.setItemText(17, _translate("Form", "18"))
        self.cmb_goal_2.setItemText(18, _translate("Form", "19"))
        self.cmb_goal_2.setItemText(19, _translate("Form", "20"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Scores()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
