# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teams.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem

from dbconnection import cursor, connection

class Ui_Teams(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1188, 861)
        Form.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #000000;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"padding: 5px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"QLabel  {\n"
"    font-size: 20px;\n"
"    color: #FFB000;\n"
"}\n"
"QLineEdit {\n"
"    font-size: 20px;\n"
"    background-color: #fff;\n"
"color: #fff;\n"
"}\n"
"QComboBox {\n"
"    font-size: 20px;\n"
"    background-color: #fff;\n"
"    color: #fff;\n"
"    border: 2px white;\n"
"    border-style: solid;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_3.setStyleSheet("background-color: #17456B;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("background-color: #0F1D2B;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.team_name = QtWidgets.QLineEdit(self.frame_5)
        self.team_name.setGeometry(QtCore.QRect(240, 80, 271, 31))
        self.team_name.setObjectName("team_name")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(80, 80, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 111, 21))
        self.label_3.setObjectName("label_3")
        self.shorthand_2 = QtWidgets.QLineEdit(self.frame_5)
        self.shorthand_2.setGeometry(QtCore.QRect(240, 180, 271, 31))
        self.shorthand_2.setObjectName("shorthand_2")
        self.league_id_combobox = QtWidgets.QComboBox(self.frame_5)
        self.league_id_combobox.setGeometry(QtCore.QRect(240, 130, 271, 31))
        self.league_id_combobox.setObjectName("league_id_combobox")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setGeometry(QtCore.QRect(320, 240, 381, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.btnSearch = QtWidgets.QPushButton(self.frame_5)
        self.btnSearch.setGeometry(QtCore.QRect(720, 240, 131, 40))
        self.btnSearch.setStyleSheet("\n"
"    color: #fff;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"padding: 5px;")
        self.btnSearch.setObjectName("btnSearch")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 1041, 51))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(470, 0, 111, 41))
        self.label_4.setStyleSheet("color: #fff;\n"
"font: bold 20px;\n"
"font-size: 30px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table = QtWidgets.QTableWidget(self.frame_4)
        self.table.clicked.connect(self.table_clicked)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.table)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setStyleSheet("background-color: #419FB7;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnInsert = QtWidgets.QPushButton(self.frame)
        self.btnInsert.setObjectName("btnInsert")
        self.btnInsert.clicked.connect(self.add_data)
        self.verticalLayout_2.addWidget(self.btnInsert)
        self.btnUpdate = QtWidgets.QPushButton(self.frame)
        self.btnUpdate.clicked.connect(self.update_data)
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout_2.addWidget(self.btnUpdate)
        self.btnDelete = QtWidgets.QPushButton(self.frame)
        self.btnDelete.clicked.connect(self.delete_data)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout_2.addWidget(self.btnDelete)
        self.btnDisplay = QtWidgets.QPushButton(self.frame)
        self.btnDisplay.clicked.connect(self.display_data)
        self.btnDisplay.setObjectName("btnDisplay")
        self.verticalLayout_2.addWidget(self.btnDisplay)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.league_id_combobox.currentIndexChanged[int].connect(self.retrieveText)
        self.fillComboBox()

    def fillComboBox(self):
        leagues = self.combobox_leagues()
        for key, value in leagues.items():
                self.league_id_combobox.addItem(key, value)

    def retrieveText(self, index):
            x = self.league_id_combobox.itemData(index)
            if x is not None:
                global combobox_league_id
                combobox_league_id = (int(x))

    def combobox_leagues(self):
        try:
            content = "SELECT league_id, league_name FROM league"
            cursor.execute(content)
            result = cursor.fetchall()

            dct = dict(map(reversed, result))
            return dct
        except mc.Error as e:
            print("Error occured")

    def display_data(self):
        try:
            cursor.execute("""SELECT league.league_name, team_name, shorhand FROM teams
                                INNER JOIN league USING(league_id);""")

            result = cursor.fetchall()

            self.table.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.table.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.table.setItem(
                        row_number, column_number, QTableWidgetItem(str(data)))
        except mc.Error as e:
            print("Error occured")

    def delete_data(self):
        try:
            content = """SELECT * FROM teams"""
            cursor.execute(content)
            result = cursor.fetchall()
        
            for row in enumerate(result):
                if row[0] == self.table.currentRow():
                    data = row[1]
                    team_id = data[0]
                    query = "DELETE FROM teams WHERE team_id = (%s)"
                    cursor.execute(query,(team_id,))
                    connection.commit()
                    self.display_data()
        except mc.Error as e:
            print("Error occured")
    
    def add_data(self):
        try:
            teamName = self.team_name.text()
            shorthand = self.shorthand_2.text()

            query = "INSERT INTO teams (league_id, team_name, shorhand) VALUES (%s,%s,%s)"
            values = (combobox_league_id,teamName,shorthand)
            cursor.execute(query,values)

            connection.commit()
            self.display_data()
        except mc.Error as e:
            print('Error occured: ',e)
   
    def update_data(self):
        try:
            leagueId = combobox_league_id
            teamName = self.team_name.text()
            shorthand = self.shorthand_2.text()

            query = "UPDATE teams SET league_id=%s, team_name = %s, shorhand = %s WHERE team_id = %s"
            value = (leagueId,teamName,shorthand,teamId)
            cursor.execute(query,value)
            connection.commit()
            self.display_data()
        except mc.Error as e:
            print('Error occured: ',e)
    
    def table_clicked(self):
        try:
            cursor.execute("""SELECT league.league_name, team_name, shorhand, team_id FROM teams
                                INNER JOIN league USING(league_id);""")
            result = cursor.fetchall()
            global teamId

            for row in enumerate(result):
                if row[0] == self.table.currentRow():
                    data = row[1]
                    leagueName = data[0]
                    teamName = data[1]
                    shorthand = data[2]
                    teamId = data[3]

                    self.shorthand_2.setText(str(shorthand))
                    self.league_id_combobox.setCurrentText(str(leagueName))
                    self.team_name.setText(str(teamName))
        except mc.Error as e:
            print("Error occured")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Team Name"))
        self.label_2.setText(_translate("Form", "League Name"))
        self.label_3.setText(_translate("Form", "Shorthand"))
        self.btnSearch.setText(_translate("Form", "SEARCH"))
        self.label_4.setText(_translate("Form", "TEAMS"))
        self.btnInsert.setText(_translate("Form", "INSERT"))
        self.btnUpdate.setText(_translate("Form", "UPDATE"))
        self.btnDelete.setText(_translate("Form", "DELETE"))
        self.btnDisplay.setText(_translate("Form", "DISPLAY"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "League Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Team Name"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Team Shorthand"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Teams()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
